use super::*;

#[derive(Clone, Copy, Debug)]
pub(crate) struct WeightParameter {
    pub(crate) name: &'static str,
    pub(crate) json_name: &'static str,
    pub(crate) groups: &'static [SweepParameterGroup],
    pub(crate) min: i32,
    pub(crate) max: i32,
    pub(crate) zero_step: i32,
    pub(crate) sweepable: bool,
}

impl WeightParameter {
    pub(crate) fn value(self, weights: EvalWeights) -> i32 {
        let value = serde_json::to_value(weights).expect("EvalWeights should serialize");
        value
            .get(self.json_name)
            .and_then(|field| field.as_i64())
            .unwrap_or(0) as i32
    }

    pub(crate) fn with_value(self, weights: EvalWeights, next: i32) -> EvalWeights {
        let mut value = serde_json::to_value(weights).expect("EvalWeights should serialize");
        let object = value
            .as_object_mut()
            .expect("EvalWeights should serialize to an object");
        object.insert(
            self.json_name.to_string(),
            serde_json::Value::Number(serde_json::Number::from(next.clamp(self.min, self.max))),
        );
        serde_json::from_value(value).expect("EvalWeights parameter metadata should be valid")
    }
}

pub(crate) fn sweep_weight_parameters(groups: &[SweepParameterGroup]) -> Vec<WeightParameter> {
    weight_parameters()
        .iter()
        .copied()
        .filter(|parameter| {
            parameter.sweepable && parameter.groups.iter().any(|group| groups.contains(group))
        })
        .collect()
}

pub(crate) fn weight_parameters() -> &'static [WeightParameter] {
    use SweepParameterGroup::*;

    &[
        WeightParameter {
            name: "king",
            json_name: "king",
            groups: &[ClassicBasic],
            min: 20_000,
            max: 20_000,
            zero_step: 0,
            sweepable: false,
        },
        WeightParameter {
            name: "common_king",
            json_name: "commonKing",
            groups: &[AlternateBasic],
            min: 0,
            max: 2_000,
            zero_step: 80,
            sweepable: true,
        },
        WeightParameter {
            name: "queen",
            json_name: "queen",
            groups: &[ClassicBasic],
            min: 100,
            max: 3_000,
            zero_step: 160,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_queen",
            json_name: "royalQueen",
            groups: &[AlternateBasic],
            min: 20_500,
            max: 20_500,
            zero_step: 0,
            sweepable: false,
        },
        WeightParameter {
            name: "princess",
            json_name: "princess",
            groups: &[AlternateBasic],
            min: 100,
            max: 3_000,
            zero_step: 140,
            sweepable: true,
        },
        WeightParameter {
            name: "rook",
            json_name: "rook",
            groups: &[ClassicBasic],
            min: 100,
            max: 2_000,
            zero_step: 100,
            sweepable: true,
        },
        WeightParameter {
            name: "bishop",
            json_name: "bishop",
            groups: &[ClassicBasic],
            min: 50,
            max: 2_000,
            zero_step: 80,
            sweepable: true,
        },
        WeightParameter {
            name: "unicorn",
            json_name: "unicorn",
            groups: &[AlternateBasic],
            min: 50,
            max: 2_000,
            zero_step: 90,
            sweepable: true,
        },
        WeightParameter {
            name: "dragon",
            json_name: "dragon",
            groups: &[AlternateBasic],
            min: 50,
            max: 2_000,
            zero_step: 120,
            sweepable: true,
        },
        WeightParameter {
            name: "knight",
            json_name: "knight",
            groups: &[ClassicBasic],
            min: 50,
            max: 2_000,
            zero_step: 80,
            sweepable: true,
        },
        WeightParameter {
            name: "pawn",
            json_name: "pawn",
            groups: &[ClassicBasic],
            min: 10,
            max: 600,
            zero_step: 30,
            sweepable: true,
        },
        WeightParameter {
            name: "brawn",
            json_name: "brawn",
            groups: &[AlternateBasic],
            min: 10,
            max: 600,
            zero_step: 30,
            sweepable: true,
        },
        WeightParameter {
            name: "check_penalty",
            json_name: "checkPenalty",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 3_000,
            zero_step: 80,
            sweepable: true,
        },
        WeightParameter {
            name: "active_timeline",
            json_name: "activeTimeline",
            groups: &[ClassicBasic, AlternateBasic],
            min: -500,
            max: 500,
            zero_step: 20,
            sweepable: true,
        },
        WeightParameter {
            name: "inactive_timeline",
            json_name: "inactiveTimeline",
            groups: &[ClassicBasic, AlternateBasic],
            min: -500,
            max: 500,
            zero_step: 20,
            sweepable: true,
        },
        WeightParameter {
            name: "present_progress",
            json_name: "presentProgress",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 200,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "mobility",
            json_name: "mobility",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 80,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "branch_penalty",
            json_name: "branchPenalty",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 300,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "advancement",
            json_name: "advancement",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 80,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "centrality",
            json_name: "centrality",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 80,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "defended_piece",
            json_name: "defendedPiece",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "attacked_piece",
            json_name: "attackedPiece",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "hanging_piece",
            json_name: "hangingPiece",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_threat",
            json_name: "royalThreat",
            groups: &[ClassicBasic, AlternateBasic],
            min: 0,
            max: 1_000,
            zero_step: 20,
            sweepable: true,
        },
        WeightParameter {
            name: "temporal_threat",
            json_name: "temporalThreat",
            groups: &[Intermediate],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "pincer_threat",
            json_name: "pincerThreat",
            groups: &[Intermediate],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "timeline_pincer",
            json_name: "timelinePincer",
            groups: &[Intermediate],
            min: 0,
            max: 500,
            zero_step: 12,
            sweepable: true,
        },
        WeightParameter {
            name: "historical_pincer",
            json_name: "historicalPincer",
            groups: &[Intermediate],
            min: 0,
            max: 500,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "frontier_tempo",
            json_name: "frontierTempo",
            groups: &[Intermediate],
            min: -100,
            max: 200,
            zero_step: 5,
            sweepable: true,
        },
        WeightParameter {
            name: "present_anchor",
            json_name: "presentAnchor",
            groups: &[Intermediate],
            min: -100,
            max: 200,
            zero_step: 5,
            sweepable: true,
        },
        WeightParameter {
            name: "development",
            json_name: "development",
            groups: &[Intermediate],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "branch_attack",
            json_name: "branchAttack",
            groups: &[Intermediate],
            min: 0,
            max: 600,
            zero_step: 12,
            sweepable: true,
        },
        WeightParameter {
            name: "check_bonus",
            json_name: "checkBonus",
            groups: &[Intermediate],
            min: 0,
            max: 2_000,
            zero_step: 24,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_capture_threat",
            json_name: "royalCaptureThreat",
            groups: &[Intermediate],
            min: 0,
            max: 3_000,
            zero_step: 30,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_capture_setup",
            json_name: "royalCaptureSetup",
            groups: &[Intermediate],
            min: 0,
            max: 6_000,
            zero_step: 80,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_escape_pressure",
            json_name: "royalEscapePressure",
            groups: &[Intermediate],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "forcing_move_pressure",
            json_name: "forcingMovePressure",
            groups: &[Intermediate],
            min: 0,
            max: 500,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "own_royal_exposure",
            json_name: "ownRoyalExposure",
            groups: &[Intermediate],
            min: 0,
            max: 3_000,
            zero_step: 30,
            sweepable: true,
        },
        WeightParameter {
            name: "fork_pressure",
            json_name: "forkPressure",
            groups: &[Intermediate],
            min: 0,
            max: 1_000,
            zero_step: 20,
            sweepable: true,
        },
        WeightParameter {
            name: "board_control",
            json_name: "boardControl",
            groups: &[Intermediate],
            min: 0,
            max: 80,
            zero_step: 3,
            sweepable: true,
        },
        WeightParameter {
            name: "piece_activity",
            json_name: "pieceActivity",
            groups: &[Intermediate],
            min: 0,
            max: 120,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "pawn_structure",
            json_name: "pawnStructure",
            groups: &[Intermediate],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "timeline_economy",
            json_name: "timelineEconomy",
            groups: &[Intermediate],
            min: 0,
            max: 400,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "present_tempo",
            json_name: "presentTempo",
            groups: &[Intermediate],
            min: -100,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_shelter",
            json_name: "royalShelter",
            groups: &[Intermediate],
            min: 0,
            max: 500,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "space_advantage",
            json_name: "spaceAdvantage",
            groups: &[Intermediate],
            min: 0,
            max: 120,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "mandatory_move_burden",
            json_name: "mandatoryMoveBurden",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "turn_completion_safety",
            json_name: "turnCompletionSafety",
            groups: &[Advanced],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "present_zugzwang",
            json_name: "presentZugzwang",
            groups: &[Advanced],
            min: 0,
            max: 600,
            zero_step: 12,
            sweepable: true,
        },
        WeightParameter {
            name: "weakest_royal_safety",
            json_name: "weakestRoyalSafety",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_liability_count",
            json_name: "royalLiabilityCount",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "multi_royal_attack",
            json_name: "multiRoyalAttack",
            groups: &[Advanced],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "defensive_bandwidth",
            json_name: "defensiveBandwidth",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "threat_overload",
            json_name: "threatOverload",
            groups: &[Advanced],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "active_branch_capacity",
            json_name: "activeBranchCapacity",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "latent_timeline_reactivation",
            json_name: "latentTimelineReactivation",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "inactive_material_quality",
            json_name: "inactiveMaterialQuality",
            groups: &[Advanced],
            min: 0,
            max: 120,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "branch_payload",
            json_name: "branchPayload",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "branch_waste",
            json_name: "branchWaste",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "timeline_compaction",
            json_name: "timelineCompaction",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "frontier_material",
            json_name: "frontierMaterial",
            groups: &[Advanced],
            min: 0,
            max: 120,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "historical_access",
            json_name: "historicalAccess",
            groups: &[Advanced],
            min: 0,
            max: 160,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "temporal_lane_control",
            json_name: "temporalLaneControl",
            groups: &[Advanced],
            min: 0,
            max: 240,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "temporal_pin",
            json_name: "temporalPin",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "temporal_skewer",
            json_name: "temporalSkewer",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "causal_battery",
            json_name: "causalBattery",
            groups: &[Advanced],
            min: 0,
            max: 240,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "arrival_square_safety",
            json_name: "arrivalSquareSafety",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "source_board_abandonment",
            json_name: "sourceBoardAbandonment",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "piece_temporal_flexibility",
            json_name: "pieceTemporalFlexibility",
            groups: &[Advanced],
            min: 0,
            max: 160,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "dimension_coverage_balance",
            json_name: "dimensionCoverageBalance",
            groups: &[Advanced],
            min: 0,
            max: 160,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "promotion_timeline_choice",
            json_name: "promotionTimelineChoice",
            groups: &[Advanced],
            min: 0,
            max: 240,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "promotion_with_check",
            json_name: "promotionWithCheck",
            groups: &[Advanced],
            min: 0,
            max: 400,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "past_royal_vulnerability",
            json_name: "pastRoyalVulnerability",
            groups: &[Advanced],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "safe_haven_boards",
            json_name: "safeHavenBoards",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "escape_branch_potential",
            json_name: "escapeBranchPotential",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "mate_net_depth_1_2",
            json_name: "mateNetDepth12",
            groups: &[Advanced],
            min: 0,
            max: 400,
            zero_step: 10,
            sweepable: true,
        },
        WeightParameter {
            name: "anti_mate_resources",
            json_name: "antiMateResources",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "checking_move_quality",
            json_name: "checkingMoveQuality",
            groups: &[Advanced],
            min: 0,
            max: 300,
            zero_step: 8,
            sweepable: true,
        },
        WeightParameter {
            name: "search_volatility",
            json_name: "searchVolatility",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "timeline_repetition_risk",
            json_name: "timelineRepetitionRisk",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "phase_by_multiverse_size",
            json_name: "phaseByMultiverseSize",
            groups: &[Advanced],
            min: 0,
            max: 120,
            zero_step: 4,
            sweepable: true,
        },
        WeightParameter {
            name: "royal_distance_in_4d",
            json_name: "royalDistanceIn4d",
            groups: &[Advanced],
            min: 0,
            max: 200,
            zero_step: 6,
            sweepable: true,
        },
        WeightParameter {
            name: "board_importance_weight",
            json_name: "boardImportanceWeight",
            groups: &[Advanced],
            min: 0,
            max: 120,
            zero_step: 4,
            sweepable: true,
        },
    ]
}
