use super::*;

impl EvalWeights {
    pub(crate) fn mutate(self, rng: &mut Lcg) -> Self {
        self.mutate_with_scale(rng, 1.0)
    }

    pub(crate) fn mutate_with_scale(self, rng: &mut Lcg, scale: f32) -> Self {
        // Keep royal values fixed so training cannot discover incentives that
        // trade away the king-shaped objective for short-term material.
        // Most children alter only a few coordinates so match outcomes can
        // identify useful directions. Occasional broad mutations preserve
        // global exploration.
        let spread = |value: i32| ((value as f32) * scale).round().max(1.0) as i32;
        let mutation_divisor = if rng.next_usize(8) == 0 { 1 } else { 24 };
        let candidate = Self {
            king: self.king,
            common_king: mutate_weight_if(
                self.common_king,
                rng,
                mutation_divisor,
                spread(80),
                0,
                2_000,
            ),
            queen: mutate_weight_if(self.queen, rng, mutation_divisor, spread(160), 100, 3_000),
            royal_queen: self.royal_queen,
            princess: mutate_weight_if(
                self.princess,
                rng,
                mutation_divisor,
                spread(140),
                100,
                3_000,
            ),
            rook: mutate_weight_if(self.rook, rng, mutation_divisor, spread(100), 100, 2_000),
            bishop: mutate_weight_if(self.bishop, rng, mutation_divisor, spread(80), 50, 2_000),
            unicorn: mutate_weight_if(self.unicorn, rng, mutation_divisor, spread(90), 50, 2_000),
            dragon: mutate_weight_if(self.dragon, rng, mutation_divisor, spread(120), 50, 2_000),
            knight: mutate_weight_if(self.knight, rng, mutation_divisor, spread(80), 50, 2_000),
            pawn: mutate_weight_if(self.pawn, rng, mutation_divisor, spread(30), 10, 600),
            brawn: mutate_weight_if(self.brawn, rng, mutation_divisor, spread(30), 10, 600),
            check_penalty: mutate_weight_if(
                self.check_penalty,
                rng,
                mutation_divisor,
                spread(80),
                0,
                3_000,
            ),
            active_timeline: mutate_weight_if(
                self.active_timeline,
                rng,
                mutation_divisor,
                spread(20),
                -500,
                500,
            ),
            inactive_timeline: mutate_weight_if(
                self.inactive_timeline,
                rng,
                mutation_divisor,
                spread(20),
                -500,
                500,
            ),
            present_progress: mutate_weight_if(
                self.present_progress,
                rng,
                mutation_divisor,
                spread(10),
                0,
                200,
            ),
            mobility: mutate_weight_if(self.mobility, rng, mutation_divisor, spread(4), 0, 80),
            branch_penalty: mutate_weight_if(
                self.branch_penalty,
                rng,
                mutation_divisor,
                spread(10),
                0,
                300,
            ),
            advancement: mutate_weight_if(
                self.advancement,
                rng,
                mutation_divisor,
                spread(4),
                0,
                80,
            ),
            centrality: mutate_weight_if(self.centrality, rng, mutation_divisor, spread(4), 0, 80),
            defended_piece: mutate_weight_if(
                self.defended_piece,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            attacked_piece: mutate_weight_if(
                self.attacked_piece,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            hanging_piece: mutate_weight_if(
                self.hanging_piece,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            royal_threat: mutate_weight_if(
                self.royal_threat,
                rng,
                mutation_divisor,
                spread(20),
                0,
                1_000,
            ),
            temporal_threat: mutate_weight_if(
                self.temporal_threat,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            pincer_threat: mutate_weight_if(
                self.pincer_threat,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            timeline_pincer: mutate_weight_if(
                self.timeline_pincer,
                rng,
                mutation_divisor,
                spread(12),
                0,
                500,
            ),
            historical_pincer: mutate_weight_if(
                self.historical_pincer,
                rng,
                mutation_divisor,
                spread(10),
                0,
                500,
            ),
            frontier_tempo: mutate_weight_if(
                self.frontier_tempo,
                rng,
                mutation_divisor,
                spread(5),
                -100,
                200,
            ),
            present_anchor: mutate_weight_if(
                self.present_anchor,
                rng,
                mutation_divisor,
                spread(5),
                -100,
                200,
            ),
            development: mutate_weight_if(
                self.development,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            branch_attack: mutate_weight_if(
                self.branch_attack,
                rng,
                mutation_divisor,
                spread(12),
                0,
                600,
            ),
            check_bonus: mutate_weight_if(
                self.check_bonus,
                rng,
                mutation_divisor,
                spread(24),
                0,
                2_000,
            ),
            royal_capture_threat: mutate_weight_if(
                self.royal_capture_threat,
                rng,
                mutation_divisor,
                spread(30),
                0,
                3_000,
            ),
            royal_capture_setup: mutate_weight_if(
                self.royal_capture_setup,
                rng,
                mutation_divisor,
                spread(80),
                0,
                6_000,
            ),
            royal_escape_pressure: mutate_weight_if(
                self.royal_escape_pressure,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            forcing_move_pressure: mutate_weight_if(
                self.forcing_move_pressure,
                rng,
                mutation_divisor,
                spread(10),
                0,
                500,
            ),
            own_royal_exposure: mutate_weight_if(
                self.own_royal_exposure,
                rng,
                mutation_divisor,
                spread(30),
                0,
                3_000,
            ),
            fork_pressure: mutate_weight_if(
                self.fork_pressure,
                rng,
                mutation_divisor,
                spread(20),
                0,
                1_000,
            ),
            board_control: mutate_weight_if(
                self.board_control,
                rng,
                mutation_divisor,
                spread(3),
                0,
                80,
            ),
            piece_activity: mutate_weight_if(
                self.piece_activity,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            pawn_structure: mutate_weight_if(
                self.pawn_structure,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            timeline_economy: mutate_weight_if(
                self.timeline_economy,
                rng,
                mutation_divisor,
                spread(8),
                0,
                400,
            ),
            present_tempo: mutate_weight_if(
                self.present_tempo,
                rng,
                mutation_divisor,
                spread(8),
                -100,
                300,
            ),
            royal_shelter: mutate_weight_if(
                self.royal_shelter,
                rng,
                mutation_divisor,
                spread(10),
                0,
                500,
            ),
            space_advantage: mutate_weight_if(
                self.space_advantage,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            mandatory_move_burden: mutate_weight_if(
                self.mandatory_move_burden,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            turn_completion_safety: mutate_weight_if(
                self.turn_completion_safety,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            present_zugzwang: mutate_weight_if(
                self.present_zugzwang,
                rng,
                mutation_divisor,
                spread(12),
                0,
                600,
            ),
            weakest_royal_safety: mutate_weight_if(
                self.weakest_royal_safety,
                rng,
                mutation_divisor,
                spread(10),
                0,
                200,
            ),
            royal_liability_count: mutate_weight_if(
                self.royal_liability_count,
                rng,
                mutation_divisor,
                spread(8),
                0,
                200,
            ),
            multi_royal_attack: mutate_weight_if(
                self.multi_royal_attack,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            defensive_bandwidth: mutate_weight_if(
                self.defensive_bandwidth,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            threat_overload: mutate_weight_if(
                self.threat_overload,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            active_branch_capacity: mutate_weight_if(
                self.active_branch_capacity,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            latent_timeline_reactivation: mutate_weight_if(
                self.latent_timeline_reactivation,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            inactive_material_quality: mutate_weight_if(
                self.inactive_material_quality,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            branch_payload: mutate_weight_if(
                self.branch_payload,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            branch_waste: mutate_weight_if(
                self.branch_waste,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            timeline_compaction: mutate_weight_if(
                self.timeline_compaction,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            frontier_material: mutate_weight_if(
                self.frontier_material,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            historical_access: mutate_weight_if(
                self.historical_access,
                rng,
                mutation_divisor,
                spread(4),
                0,
                160,
            ),
            temporal_lane_control: mutate_weight_if(
                self.temporal_lane_control,
                rng,
                mutation_divisor,
                spread(6),
                0,
                240,
            ),
            temporal_pin: mutate_weight_if(
                self.temporal_pin,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            temporal_skewer: mutate_weight_if(
                self.temporal_skewer,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            causal_battery: mutate_weight_if(
                self.causal_battery,
                rng,
                mutation_divisor,
                spread(6),
                0,
                240,
            ),
            arrival_square_safety: mutate_weight_if(
                self.arrival_square_safety,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            source_board_abandonment: mutate_weight_if(
                self.source_board_abandonment,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            piece_temporal_flexibility: mutate_weight_if(
                self.piece_temporal_flexibility,
                rng,
                mutation_divisor,
                spread(4),
                0,
                160,
            ),
            dimension_coverage_balance: mutate_weight_if(
                self.dimension_coverage_balance,
                rng,
                mutation_divisor,
                spread(4),
                0,
                160,
            ),
            promotion_timeline_choice: mutate_weight_if(
                self.promotion_timeline_choice,
                rng,
                mutation_divisor,
                spread(6),
                0,
                240,
            ),
            promotion_with_check: mutate_weight_if(
                self.promotion_with_check,
                rng,
                mutation_divisor,
                spread(8),
                0,
                400,
            ),
            past_royal_vulnerability: mutate_weight_if(
                self.past_royal_vulnerability,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            safe_haven_boards: mutate_weight_if(
                self.safe_haven_boards,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            escape_branch_potential: mutate_weight_if(
                self.escape_branch_potential,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            mate_net_depth_1_2: mutate_weight_if(
                self.mate_net_depth_1_2,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            anti_mate_resources: mutate_weight_if(
                self.anti_mate_resources,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            checking_move_quality: mutate_weight_if(
                self.checking_move_quality,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            search_volatility: mutate_weight_if(
                self.search_volatility,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            timeline_repetition_risk: mutate_weight_if(
                self.timeline_repetition_risk,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            phase_by_multiverse_size: mutate_weight_if(
                self.phase_by_multiverse_size,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            royal_distance_in_4d: mutate_weight_if(
                self.royal_distance_in_4d,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            board_importance_weight: mutate_weight_if(
                self.board_importance_weight,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
        };
        if candidate == self {
            self.mutate_with_scale(rng, scale)
        } else {
            candidate
        }
    }

    pub(crate) fn crossover(left: Self, right: Self, rng: &mut Lcg) -> Self {
        // Uniform crossover lets each parameter independently come from either
        // parent, which fits this compact, flat genome.
        macro_rules! pick {
            ($field:ident) => {
                if rng.next_bool() {
                    left.$field
                } else {
                    right.$field
                }
            };
        }
        Self {
            king: left.king,
            common_king: pick!(common_king),
            queen: pick!(queen),
            royal_queen: left.royal_queen,
            princess: pick!(princess),
            rook: pick!(rook),
            bishop: pick!(bishop),
            unicorn: pick!(unicorn),
            dragon: pick!(dragon),
            knight: pick!(knight),
            pawn: pick!(pawn),
            brawn: pick!(brawn),
            check_penalty: pick!(check_penalty),
            active_timeline: pick!(active_timeline),
            inactive_timeline: pick!(inactive_timeline),
            present_progress: pick!(present_progress),
            mobility: pick!(mobility),
            branch_penalty: pick!(branch_penalty),
            advancement: pick!(advancement),
            centrality: pick!(centrality),
            defended_piece: pick!(defended_piece),
            attacked_piece: pick!(attacked_piece),
            hanging_piece: pick!(hanging_piece),
            royal_threat: pick!(royal_threat),
            temporal_threat: pick!(temporal_threat),
            pincer_threat: pick!(pincer_threat),
            timeline_pincer: pick!(timeline_pincer),
            historical_pincer: pick!(historical_pincer),
            frontier_tempo: pick!(frontier_tempo),
            present_anchor: pick!(present_anchor),
            development: pick!(development),
            branch_attack: pick!(branch_attack),
            check_bonus: pick!(check_bonus),
            royal_capture_threat: pick!(royal_capture_threat),
            royal_capture_setup: pick!(royal_capture_setup),
            royal_escape_pressure: pick!(royal_escape_pressure),
            forcing_move_pressure: pick!(forcing_move_pressure),
            own_royal_exposure: pick!(own_royal_exposure),
            fork_pressure: pick!(fork_pressure),
            board_control: pick!(board_control),
            piece_activity: pick!(piece_activity),
            pawn_structure: pick!(pawn_structure),
            timeline_economy: pick!(timeline_economy),
            present_tempo: pick!(present_tempo),
            royal_shelter: pick!(royal_shelter),
            space_advantage: pick!(space_advantage),
            mandatory_move_burden: pick!(mandatory_move_burden),
            turn_completion_safety: pick!(turn_completion_safety),
            present_zugzwang: pick!(present_zugzwang),
            weakest_royal_safety: pick!(weakest_royal_safety),
            royal_liability_count: pick!(royal_liability_count),
            multi_royal_attack: pick!(multi_royal_attack),
            defensive_bandwidth: pick!(defensive_bandwidth),
            threat_overload: pick!(threat_overload),
            active_branch_capacity: pick!(active_branch_capacity),
            latent_timeline_reactivation: pick!(latent_timeline_reactivation),
            inactive_material_quality: pick!(inactive_material_quality),
            branch_payload: pick!(branch_payload),
            branch_waste: pick!(branch_waste),
            timeline_compaction: pick!(timeline_compaction),
            frontier_material: pick!(frontier_material),
            historical_access: pick!(historical_access),
            temporal_lane_control: pick!(temporal_lane_control),
            temporal_pin: pick!(temporal_pin),
            temporal_skewer: pick!(temporal_skewer),
            causal_battery: pick!(causal_battery),
            arrival_square_safety: pick!(arrival_square_safety),
            source_board_abandonment: pick!(source_board_abandonment),
            piece_temporal_flexibility: pick!(piece_temporal_flexibility),
            dimension_coverage_balance: pick!(dimension_coverage_balance),
            promotion_timeline_choice: pick!(promotion_timeline_choice),
            promotion_with_check: pick!(promotion_with_check),
            past_royal_vulnerability: pick!(past_royal_vulnerability),
            safe_haven_boards: pick!(safe_haven_boards),
            escape_branch_potential: pick!(escape_branch_potential),
            mate_net_depth_1_2: pick!(mate_net_depth_1_2),
            anti_mate_resources: pick!(anti_mate_resources),
            checking_move_quality: pick!(checking_move_quality),
            search_volatility: pick!(search_volatility),
            timeline_repetition_risk: pick!(timeline_repetition_risk),
            phase_by_multiverse_size: pick!(phase_by_multiverse_size),
            royal_distance_in_4d: pick!(royal_distance_in_4d),
            board_importance_weight: pick!(board_importance_weight),
        }
    }

    pub(crate) fn to_json(self) -> String {
        serde_json::to_string(&self).expect("EvalWeights should serialize")
    }

    pub(crate) fn from_json(value: &str) -> Result<Self, String> {
        serde_json::from_str(value).map_err(|error| error.to_string())
    }
}

impl Lcg {
    pub(crate) fn new(seed: u64) -> Self {
        Self { state: seed.max(1) }
    }

    pub(crate) fn next_u64(&mut self) -> u64 {
        self.state = self
            .state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1);
        self.state
    }

    pub(crate) fn next_usize(&mut self, upper: usize) -> usize {
        (self.next_u64() as usize) % upper.max(1)
    }

    pub(crate) fn next_bool(&mut self) -> bool {
        self.next_u64() & 1 == 1
    }
}
