use super::*;
use crate::cpu::{EvalWeights, SearchContext, SearchInstant};

pub(crate) fn seeded_start_position(
    seed: u64,
    config: &CpuCliConfig,
    deadline: Option<SearchInstant>,
) -> Game {
    if seed.is_multiple_of(5) {
        return mate_training_position(seed);
    }

    let mut rng = Lcg::new(seed);
    let mut game = Game::new();
    let plies = rng.next_usize(3);
    for _ in 0..plies {
        if training_expired(deadline) {
            break;
        }
        let mut context = SearchContext::new(
            EvalWeights::default_tuned(),
            game.turn,
            (config.nodes / 2).max(20),
            deadline,
        );
        let plan_limit = context.root_plan_limit();
        let plans = game.legal_turn_plans_with_context(&mut context, plan_limit);
        if plans.is_empty() {
            break;
        }
        let index = rng.next_usize(plans.len().min(8));
        let Some(next) = game.apply_turn_plan_for_search(&plans[index]) else {
            break;
        };
        game = next;
        context.nodes += 1;
    }
    game
}

pub(crate) fn mate_training_position(seed: u64) -> Game {
    // Tactical fixtures are generated by starting from an immediate royal-capture
    // board and moving the attacking rook one or two squares backward. If either
    // side discovers a shorter mate, the fixture still serves its purpose: it
    // becomes a blunder detector instead of a horizon test.
    let attacker = if seed & 1 == 0 {
        Color::White
    } else {
        Color::Black
    };
    let defender = attacker.opposite();
    let mut board = [[None; 8]; 8];
    let (attacker_king_y, defender_king_y, rook_y) = match attacker {
        Color::White => (0, 5, 1 + (seed as i32 % 2)),
        Color::Black => (7, 2, 6 - (seed as i32 % 2)),
    };
    board[attacker_king_y as usize][4] = Some(Piece {
        color: attacker,
        piece_type: PieceType::King,
    });
    board[defender_king_y as usize][3] = Some(Piece {
        color: defender,
        piece_type: PieceType::King,
    });
    board[rook_y as usize][3] = Some(Piece {
        color: attacker,
        piece_type: PieceType::Rook,
    });

    let mut game = Game::new();
    game.turn = attacker;
    game.timelines[0].boards = vec![BoardSnapshot {
        time: 0,
        side_to_move: attacker,
        board,
        castling: CastlingRights::new(),
        en_passant: None,
        origin: Origin::None,
    }];
    game
}
