use super::*;
use crate::cpu::EvalWeights;

impl EvalWeights {
    pub(crate) fn mutate(self, rng: &mut Lcg) -> Self {
        self.mutate_with_scale(rng, 1.0)
    }

    pub(crate) fn mutate_with_scale(self, rng: &mut Lcg, scale: f32) -> Self {
        // Keep royal values fixed so training cannot discover incentives that
        // trade away the king-shaped objective for short-term material.
        // Most children alter only a few coordinates so match outcomes can
        // identify useful directions. Occasional broad mutations preserve
        // global exploration.
        let spread = |value: i32| ((value as f32) * scale).round().max(1.0) as i32;
        let mutation_divisor = if rng.next_usize(8) == 0 { 1 } else { 24 };
        let candidate = Self {
            king: self.king,
            common_king: mutate_weight_if(
                self.common_king,
                rng,
                mutation_divisor,
                spread(80),
                0,
                2_000,
            ),
            queen: mutate_weight_if(self.queen, rng, mutation_divisor, spread(160), 100, 3_000),
            royal_queen: self.royal_queen,
            princess: mutate_weight_if(
                self.princess,
                rng,
                mutation_divisor,
                spread(140),
                100,
                3_000,
            ),
            rook: mutate_weight_if(self.rook, rng, mutation_divisor, spread(100), 100, 2_000),
            bishop: mutate_weight_if(self.bishop, rng, mutation_divisor, spread(80), 50, 2_000),
            unicorn: mutate_weight_if(self.unicorn, rng, mutation_divisor, spread(90), 50, 2_000),
            dragon: mutate_weight_if(self.dragon, rng, mutation_divisor, spread(120), 50, 2_000),
            knight: mutate_weight_if(self.knight, rng, mutation_divisor, spread(80), 50, 2_000),
            pawn: mutate_weight_if(self.pawn, rng, mutation_divisor, spread(30), 10, 600),
            brawn: mutate_weight_if(self.brawn, rng, mutation_divisor, spread(30), 10, 600),
            check_penalty: mutate_weight_if(
                self.check_penalty,
                rng,
                mutation_divisor,
                spread(80),
                0,
                3_000,
            ),
            active_timeline: mutate_weight_if(
                self.active_timeline,
                rng,
                mutation_divisor,
                spread(20),
                -500,
                500,
            ),
            inactive_timeline: mutate_weight_if(
                self.inactive_timeline,
                rng,
                mutation_divisor,
                spread(20),
                -500,
                500,
            ),
            present_progress: mutate_weight_if(
                self.present_progress,
                rng,
                mutation_divisor,
                spread(10),
                0,
                200,
            ),
            mobility: mutate_weight_if(self.mobility, rng, mutation_divisor, spread(4), 0, 80),
            branch_penalty: mutate_weight_if(
                self.branch_penalty,
                rng,
                mutation_divisor,
                spread(10),
                0,
                300,
            ),
            advancement: mutate_weight_if(
                self.advancement,
                rng,
                mutation_divisor,
                spread(4),
                0,
                80,
            ),
            centrality: mutate_weight_if(self.centrality, rng, mutation_divisor, spread(4), 0, 80),
            defended_piece: mutate_weight_if(
                self.defended_piece,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            attacked_piece: mutate_weight_if(
                self.attacked_piece,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            hanging_piece: mutate_weight_if(
                self.hanging_piece,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            royal_threat: mutate_weight_if(
                self.royal_threat,
                rng,
                mutation_divisor,
                spread(20),
                0,
                1_000,
            ),
            temporal_threat: mutate_weight_if(
                self.temporal_threat,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            pincer_threat: mutate_weight_if(
                self.pincer_threat,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            timeline_pincer: mutate_weight_if(
                self.timeline_pincer,
                rng,
                mutation_divisor,
                spread(12),
                0,
                500,
            ),
            historical_pincer: mutate_weight_if(
                self.historical_pincer,
                rng,
                mutation_divisor,
                spread(10),
                0,
                500,
            ),
            frontier_tempo: mutate_weight_if(
                self.frontier_tempo,
                rng,
                mutation_divisor,
                spread(5),
                -100,
                200,
            ),
            present_anchor: mutate_weight_if(
                self.present_anchor,
                rng,
                mutation_divisor,
                spread(5),
                -100,
                200,
            ),
            development: mutate_weight_if(
                self.development,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            branch_attack: mutate_weight_if(
                self.branch_attack,
                rng,
                mutation_divisor,
                spread(12),
                0,
                600,
            ),
            check_bonus: mutate_weight_if(
                self.check_bonus,
                rng,
                mutation_divisor,
                spread(24),
                0,
                2_000,
            ),
            royal_capture_threat: mutate_weight_if(
                self.royal_capture_threat,
                rng,
                mutation_divisor,
                spread(30),
                0,
                3_000,
            ),
            royal_capture_setup: mutate_weight_if(
                self.royal_capture_setup,
                rng,
                mutation_divisor,
                spread(80),
                0,
                6_000,
            ),
            royal_escape_pressure: mutate_weight_if(
                self.royal_escape_pressure,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            forcing_move_pressure: mutate_weight_if(
                self.forcing_move_pressure,
                rng,
                mutation_divisor,
                spread(10),
                0,
                500,
            ),
            own_royal_exposure: mutate_weight_if(
                self.own_royal_exposure,
                rng,
                mutation_divisor,
                spread(30),
                0,
                3_000,
            ),
            fork_pressure: mutate_weight_if(
                self.fork_pressure,
                rng,
                mutation_divisor,
                spread(20),
                0,
                1_000,
            ),
            board_control: mutate_weight_if(
                self.board_control,
                rng,
                mutation_divisor,
                spread(3),
                0,
                80,
            ),
            piece_activity: mutate_weight_if(
                self.piece_activity,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            pawn_structure: mutate_weight_if(
                self.pawn_structure,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            timeline_economy: mutate_weight_if(
                self.timeline_economy,
                rng,
                mutation_divisor,
                spread(8),
                0,
                400,
            ),
            present_tempo: mutate_weight_if(
                self.present_tempo,
                rng,
                mutation_divisor,
                spread(8),
                -100,
                300,
            ),
            royal_shelter: mutate_weight_if(
                self.royal_shelter,
                rng,
                mutation_divisor,
                spread(10),
                0,
                500,
            ),
            space_advantage: mutate_weight_if(
                self.space_advantage,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            mandatory_move_burden: mutate_weight_if(
                self.mandatory_move_burden,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            turn_completion_safety: mutate_weight_if(
                self.turn_completion_safety,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            present_zugzwang: mutate_weight_if(
                self.present_zugzwang,
                rng,
                mutation_divisor,
                spread(12),
                0,
                600,
            ),
            weakest_royal_safety: mutate_weight_if(
                self.weakest_royal_safety,
                rng,
                mutation_divisor,
                spread(10),
                0,
                200,
            ),
            royal_liability_count: mutate_weight_if(
                self.royal_liability_count,
                rng,
                mutation_divisor,
                spread(8),
                0,
                200,
            ),
            multi_royal_attack: mutate_weight_if(
                self.multi_royal_attack,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            defensive_bandwidth: mutate_weight_if(
                self.defensive_bandwidth,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            threat_overload: mutate_weight_if(
                self.threat_overload,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            active_branch_capacity: mutate_weight_if(
                self.active_branch_capacity,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            latent_timeline_reactivation: mutate_weight_if(
                self.latent_timeline_reactivation,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            inactive_material_quality: mutate_weight_if(
                self.inactive_material_quality,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            branch_payload: mutate_weight_if(
                self.branch_payload,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            branch_waste: mutate_weight_if(
                self.branch_waste,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            timeline_compaction: mutate_weight_if(
                self.timeline_compaction,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            frontier_material: mutate_weight_if(
                self.frontier_material,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            historical_access: mutate_weight_if(
                self.historical_access,
                rng,
                mutation_divisor,
                spread(4),
                0,
                160,
            ),
            temporal_lane_control: mutate_weight_if(
                self.temporal_lane_control,
                rng,
                mutation_divisor,
                spread(6),
                0,
                240,
            ),
            temporal_pin: mutate_weight_if(
                self.temporal_pin,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            temporal_skewer: mutate_weight_if(
                self.temporal_skewer,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            causal_battery: mutate_weight_if(
                self.causal_battery,
                rng,
                mutation_divisor,
                spread(6),
                0,
                240,
            ),
            arrival_square_safety: mutate_weight_if(
                self.arrival_square_safety,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            source_board_abandonment: mutate_weight_if(
                self.source_board_abandonment,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            piece_temporal_flexibility: mutate_weight_if(
                self.piece_temporal_flexibility,
                rng,
                mutation_divisor,
                spread(4),
                0,
                160,
            ),
            dimension_coverage_balance: mutate_weight_if(
                self.dimension_coverage_balance,
                rng,
                mutation_divisor,
                spread(4),
                0,
                160,
            ),
            promotion_timeline_choice: mutate_weight_if(
                self.promotion_timeline_choice,
                rng,
                mutation_divisor,
                spread(6),
                0,
                240,
            ),
            promotion_with_check: mutate_weight_if(
                self.promotion_with_check,
                rng,
                mutation_divisor,
                spread(8),
                0,
                400,
            ),
            past_royal_vulnerability: mutate_weight_if(
                self.past_royal_vulnerability,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            safe_haven_boards: mutate_weight_if(
                self.safe_haven_boards,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            escape_branch_potential: mutate_weight_if(
                self.escape_branch_potential,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            mate_net_depth_1_2: mutate_weight_if(
                self.mate_net_depth_1_2,
                rng,
                mutation_divisor,
                spread(10),
                0,
                400,
            ),
            anti_mate_resources: mutate_weight_if(
                self.anti_mate_resources,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            checking_move_quality: mutate_weight_if(
                self.checking_move_quality,
                rng,
                mutation_divisor,
                spread(8),
                0,
                300,
            ),
            search_volatility: mutate_weight_if(
                self.search_volatility,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            timeline_repetition_risk: mutate_weight_if(
                self.timeline_repetition_risk,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            phase_by_multiverse_size: mutate_weight_if(
                self.phase_by_multiverse_size,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
            royal_distance_in_4d: mutate_weight_if(
                self.royal_distance_in_4d,
                rng,
                mutation_divisor,
                spread(6),
                0,
                200,
            ),
            board_importance_weight: mutate_weight_if(
                self.board_importance_weight,
                rng,
                mutation_divisor,
                spread(4),
                0,
                120,
            ),
        };
        if candidate == self {
            self.mutate_with_scale(rng, scale)
        } else {
            candidate
        }
    }
}
