export const GPU_CANDIDATE_STRIDE = 24;
export const GPU_SOURCE_STRIDE = 10;
export const GPU_TARGET_STRIDE = 10;
export const GPU_BOARD_STRIDE = 73;
export const GPU_MUTATION_BOARD_STRIDE = 76;
export const GPU_MUTATION_CHILD_STRIDE = GPU_MUTATION_BOARD_STRIDE * 2;
export const GPU_MUTATION_STATUS_OK = 1;
export const GPU_MUTATION_STATUS_ROYAL_CAPTURE = 2;
export const GPU_MUTATION_STATUS_BRANCH_OK = 3;
export const GPU_MUTATION_STATUS_BRANCH_ROYAL_CAPTURE = 4;
export const GPU_TURN_STATUS_RECORD_STRIDE = 4;

// GPU-resident search layout. Retained frontier states are materialized so move
// generation can read them without following pointer chains. Expanded children
// remain parent-plus-delta records until pruning chooses the next frontier.
export const GPU_FRONTIER_HEADER_STRIDE = 16;
export const GPU_FRONTIER_BOARD_STRIDE = 78;
export const GPU_FRONTIER_BOARD_TIMELINE_ID = 0;
export const GPU_FRONTIER_BOARD_ROW = 1;
export const GPU_FRONTIER_BOARD_OWNER = 2;
export const GPU_FRONTIER_BOARD_TIME = 3;
export const GPU_FRONTIER_BOARD_SIDE_TO_MOVE = 4;
export const GPU_FRONTIER_BOARD_CASTLING = 5;
export const GPU_FRONTIER_BOARD_EN_PASSANT = 6;
export const GPU_FRONTIER_BOARD_LATEST = 10;
export const GPU_FRONTIER_BOARD_ORIGIN = 11;
export const GPU_FRONTIER_BOARD_SQUARES = 12;
export const GPU_FRONTIER_BOARD_ACTIVE = 76;
export const GPU_FRONTIER_BOARD_PENDING = 77;
export const GPU_FRONTIER_MAX_PLAN_MOVES = 64;
export const GPU_FRONTIER_MAX_DEPTH = 16;
export const GPU_FRONTIER_ANCESTRY_STRIDE = GPU_FRONTIER_MAX_DEPTH;
export const GPU_FRONTIER_MOVE_STRIDE = 8;
export const GPU_FRONTIER_PLAN_STRIDE = GPU_FRONTIER_MAX_PLAN_MOVES * GPU_FRONTIER_MOVE_STRIDE;
export const GPU_FRONTIER_PLAN_OFFSET = GPU_FRONTIER_HEADER_STRIDE + GPU_FRONTIER_ANCESTRY_STRIDE;
export const GPU_FRONTIER_BOARD_OFFSET = GPU_FRONTIER_PLAN_OFFSET + GPU_FRONTIER_PLAN_STRIDE;
export const GPU_FRONTIER_CANDIDATE_STRIDE = 24;
export const GPU_FRONTIER_DELTA_STRIDE = GPU_FRONTIER_BOARD_STRIDE * 2;
export const GPU_FRONTIER_SUMMARY_STRIDE = 12;

export const GPU_FRONTIER_HEADER_PARENT = 0;
export const GPU_FRONTIER_HEADER_ROOT = 1;
export const GPU_FRONTIER_HEADER_SCORE = 2;
export const GPU_FRONTIER_HEADER_DEPTH = 3;
export const GPU_FRONTIER_HEADER_TURN = 4;
export const GPU_FRONTIER_HEADER_BOARD_COUNT = 5;
export const GPU_FRONTIER_HEADER_PLAN_LENGTH = 6;
export const GPU_FRONTIER_HEADER_COMPLETE = 7;
export const GPU_FRONTIER_HEADER_TERMINAL = 8;
export const GPU_FRONTIER_HEADER_HASH_LOW = 9;
export const GPU_FRONTIER_HEADER_HASH_HIGH = 10;
export const GPU_FRONTIER_HEADER_NEXT_WHITE_TIMELINE = 11;
export const GPU_FRONTIER_HEADER_NEXT_BLACK_TIMELINE = 12;
export const GPU_FRONTIER_HEADER_PRESENT_TIME = 13;
export const GPU_FRONTIER_HEADER_PENDING_BOARDS = 14;
export const GPU_FRONTIER_HEADER_FLAGS = 15;
