function queryElement<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector);
  if (!element) {
    throw new Error(`Missing required element ${selector}.`);
  }
  return element;
}

// Centralized DOM lookups keep main.js focused on engine/network state and make
// the required index.html ids explicit.
export const elements = {
  multiverse: queryElement<HTMLElement>("#multiverse"),
  timelineGrid: queryElement<HTMLElement>("#timeline-grid"),
  evaluationBar: queryElement<HTMLElement>("#evaluation-bar"),
  evaluationWhite: queryElement<HTMLElement>("#evaluation-white"),
  evaluationScore: queryElement<HTMLElement>("#evaluation-score"),
  message: queryElement<HTMLElement>("#message"),
  appStatus: queryElement<HTMLElement>("#app-status"),
  wasmStatus: queryElement<HTMLElement>("#wasm-status"),
  serverStatus: queryElement<HTMLElement>("#server-status"),
  hud: queryElement<HTMLElement>("#hud"),
  toggleHudButton: queryElement<HTMLButtonElement>("#toggle-hud"),
  openTrainingButton: queryElement<HTMLButtonElement>("#open-training"),
  closeTrainingButton: queryElement<HTMLButtonElement>("#close-training"),
  trainingModal: queryElement<HTMLElement>("#training-modal"),
  resetButton: queryElement<HTMLButtonElement>("#reset-game"),
  undoMoveButton: queryElement<HTMLButtonElement>("#undo-move"),
  submitTurnButton: queryElement<HTMLButtonElement>("#submit-turn"),
  clearPlansButton: queryElement<HTMLButtonElement>("#clear-plans"),
  concedeButton: queryElement<HTMLButtonElement>("#concede-game"),
  roomInput: queryElement<HTMLInputElement>("#room-id"),
  whitePlayerSelect: queryElement<HTMLSelectElement>("#white-player"),
  blackPlayerSelect: queryElement<HTMLSelectElement>("#black-player"),
  customCpuModal: queryElement<HTMLElement>("#custom-cpu-modal"),
  customCpuPanel: queryElement<HTMLElement>("#custom-cpu-panel"),
  closeCustomCpuButton: queryElement<HTMLButtonElement>("#close-custom-cpu"),
  saveCustomCpuButton: queryElement<HTMLButtonElement>("#save-custom-cpu"),
  resetCustomCpuButton: queryElement<HTMLButtonElement>("#reset-custom-cpu"),
  customCpuDepthInput: queryElement<HTMLInputElement>("#custom-cpu-depth"),
  customCpuMinDepthInput: queryElement<HTMLInputElement>("#custom-cpu-min-depth"),
  customCpuNodesInput: queryElement<HTMLInputElement>("#custom-cpu-nodes"),
  customCpuTimeMsInput: queryElement<HTMLInputElement>("#custom-cpu-time-ms"),
  customCpuSearchStrategyInput: queryElement<HTMLSelectElement>("#custom-cpu-search-strategy"),
  customGpuModal: queryElement<HTMLElement>("#custom-gpu-modal"),
  customGpuPanel: queryElement<HTMLElement>("#custom-gpu-panel"),
  closeCustomGpuButton: queryElement<HTMLButtonElement>("#close-custom-gpu"),
  saveCustomGpuButton: queryElement<HTMLButtonElement>("#save-custom-gpu"),
  resetCustomGpuButton: queryElement<HTMLButtonElement>("#reset-custom-gpu"),
  customGpuDepthInput: queryElement<HTMLInputElement>("#custom-gpu-depth"),
  customGpuMinDepthInput: queryElement<HTMLInputElement>("#custom-gpu-min-depth"),
  customGpuNodesInput: queryElement<HTMLInputElement>("#custom-gpu-nodes"),
  customGpuTimeMsInput: queryElement<HTMLInputElement>("#custom-gpu-time-ms"),
  startGameButton: queryElement<HTMLButtonElement>("#start-game"),
  joinWhiteButton: queryElement<HTMLButtonElement>("#join-white"),
  joinBlackButton: queryElement<HTMLButtonElement>("#join-black"),
  joinSpectatorButton: queryElement<HTMLButtonElement>("#join-spectator"),
  multiplayerStatus: queryElement<HTMLElement>("#multiplayer-status"),
  shareLink: queryElement<HTMLAnchorElement>("#share-link"),
  trainingPanel: queryElement<HTMLElement>("#training-panel"),
  trainingModeSelect: queryElement<HTMLSelectElement>("#training-mode"),
  trainingPresetButtons: Array.from(document.querySelectorAll<HTMLButtonElement>("[data-training-preset]")),
  trainingTabButtons: Array.from(document.querySelectorAll<HTMLButtonElement>("[data-training-tab]")),
  trainingTabPanels: Array.from(document.querySelectorAll<HTMLElement>("[data-training-panel]")),
  trainingSamplesInput: queryElement<HTMLInputElement>("#training-samples"),
  trainingSelfPlayWorkersInput: queryElement<HTMLInputElement>("#training-self-play-workers"),
  trainingSearchWorkersInput: queryElement<HTMLInputElement>("#training-search-workers"),
  trainingTemperatureInput: queryElement<HTMLInputElement>("#training-temperature"),
  trainingDepthInput: queryElement<HTMLInputElement>("#training-depth"),
  trainingNodesInput: queryElement<HTMLInputElement>("#training-nodes"),
  trainingRateInput: queryElement<HTMLInputElement>("#training-rate"),
  trainingEpochsInput: queryElement<HTMLInputElement>("#training-epochs"),
  trainingBufferInput: queryElement<HTMLInputElement>("#training-buffer"),
  trainingBatchInput: queryElement<HTMLInputElement>("#training-batch"),
  trainingValidationInput: queryElement<HTMLInputElement>("#training-validation"),
  trainingLossLogReplayInput: queryElement<HTMLInputElement>("#training-loss-log-replay"),
  trainingValidationIntervalInput: queryElement<HTMLInputElement>("#training-validation-interval"),
  trainingPatienceInput: queryElement<HTMLInputElement>("#training-patience"),
  trainingDecayInput: queryElement<HTMLInputElement>("#training-decay"),
  trainingCpuDepthInput: queryElement<HTMLInputElement>("#training-cpu-depth"),
  trainingCpuModeSelect: queryElement<HTMLSelectElement>("#training-cpu-mode"),
  trainingCpuNodesInput: queryElement<HTMLInputElement>("#training-cpu-nodes"),
  trainingCpuTimeMsInput: queryElement<HTMLInputElement>("#training-cpu-time-ms"),
  trainingCpuCandidatesInput: queryElement<HTMLInputElement>("#training-cpu-candidates"),
  trainingCpuFinalistsInput: queryElement<HTMLInputElement>("#training-cpu-finalists"),
  trainingCpuPairBatchInput: queryElement<HTMLInputElement>("#training-cpu-pair-batch"),
  trainingCpuOpponentVariantsInput: queryElement<HTMLInputElement>("#training-cpu-opponent-variants"),
  trainingCpuScreeningOpponentVariantsInput: queryElement<HTMLInputElement>("#training-cpu-screening-opponent-variants"),
  trainingCpuRoundsPerVariantInput: queryElement<HTMLInputElement>("#training-cpu-rounds-per-variant"),
  trainingCpuHallOfFameEntriesInput: queryElement<HTMLInputElement>("#training-cpu-hall-of-fame-entries"),
  trainingCpuLeagueContendersInput: queryElement<HTMLInputElement>("#training-cpu-league-contenders"),
  trainingCpuLeagueHallOfFameEntriesInput: queryElement<HTMLInputElement>("#training-cpu-league-hall-of-fame-entries"),
  trainingCpuMinPairsInput: queryElement<HTMLInputElement>("#training-cpu-min-pairs"),
  trainingCpuMaxPairsInput: queryElement<HTMLInputElement>("#training-cpu-max-pairs"),
  trainingCpuDrawWindowInput: queryElement<HTMLInputElement>("#training-cpu-draw-window"),
  trainingCpuDrawRateLimitInput: queryElement<HTMLInputElement>("#training-cpu-draw-rate-limit"),
  trainingCpuMaxMatchPliesInput: queryElement<HTMLInputElement>("#training-cpu-max-match-plies"),
  trainingCpuMaxMatchTimeMsInput: queryElement<HTMLInputElement>("#training-cpu-max-match-time-ms"),
  trainingCpuMaxGenerationsWithoutCandidateInput: queryElement<HTMLInputElement>("#training-cpu-max-generations-without-candidate"),
  trainingCpuWorkersInput: queryElement<HTMLInputElement>("#training-cpu-workers"),
  trainingCpuSecondsInput: queryElement<HTMLInputElement>("#training-cpu-seconds"),
  startTrainingButton: queryElement<HTMLButtonElement>("#start-training"),
  stopTrainingButton: queryElement<HTMLButtonElement>("#stop-training"),
  trainingStatus: queryElement<HTMLElement>("#training-status"),
  trainingStatusView: queryElement<HTMLElement>("#training-status-view"),
  trainingProgress: queryElement<HTMLElement>("#training-progress")
};
