export const elements = {
  timelineGrid: document.querySelector("#timeline-grid"),
  message: document.querySelector("#message"),
  wasmStatus: document.querySelector("#wasm-status"),
  serverStatus: document.querySelector("#server-status"),
  hud: document.querySelector("#hud"),
  toggleHudButton: document.querySelector("#toggle-hud"),
  resetButton: document.querySelector("#reset-game"),
  undoMoveButton: document.querySelector("#undo-move"),
  submitTurnButton: document.querySelector("#submit-turn"),
  roomInput: document.querySelector("#room-id"),
  joinWhiteButton: document.querySelector("#join-white"),
  joinBlackButton: document.querySelector("#join-black"),
  joinSpectatorButton: document.querySelector("#join-spectator"),
  botWhiteButton: document.querySelector("#bot-white"),
  botBlackButton: document.querySelector("#bot-black"),
  multiplayerStatus: document.querySelector("#multiplayer-status"),
  botStatus: document.querySelector("#bot-status"),
  shareLink: document.querySelector("#share-link")
};
