// Centralized DOM lookups keep main.js focused on engine/network state and make
// the required index.html ids explicit.
export const elements = {
  multiverse: document.querySelector("#multiverse"),
  timelineGrid: document.querySelector("#timeline-grid"),
  evaluationBar: document.querySelector("#evaluation-bar"),
  evaluationWhite: document.querySelector("#evaluation-white"),
  evaluationScore: document.querySelector("#evaluation-score"),
  message: document.querySelector("#message"),
  wasmStatus: document.querySelector("#wasm-status"),
  serverStatus: document.querySelector("#server-status"),
  hud: document.querySelector("#hud"),
  toggleHudButton: document.querySelector("#toggle-hud"),
  resetButton: document.querySelector("#reset-game"),
  undoMoveButton: document.querySelector("#undo-move"),
  submitTurnButton: document.querySelector("#submit-turn"),
  concedeButton: document.querySelector("#concede-game"),
  roomInput: document.querySelector("#room-id"),
  whitePlayerSelect: document.querySelector("#white-player"),
  blackPlayerSelect: document.querySelector("#black-player"),
  startGameButton: document.querySelector("#start-game"),
  joinWhiteButton: document.querySelector("#join-white"),
  joinBlackButton: document.querySelector("#join-black"),
  joinSpectatorButton: document.querySelector("#join-spectator"),
  multiplayerStatus: document.querySelector("#multiplayer-status"),
  shareLink: document.querySelector("#share-link"),
  trainingPanel: document.querySelector("#training-panel"),
  trainingSamplesInput: document.querySelector("#training-samples"),
  trainingDepthInput: document.querySelector("#training-depth"),
  trainingNodesInput: document.querySelector("#training-nodes"),
  trainingRateInput: document.querySelector("#training-rate"),
  trainingEpochsInput: document.querySelector("#training-epochs"),
  trainingBufferInput: document.querySelector("#training-buffer"),
  startTrainingButton: document.querySelector("#start-training"),
  stopTrainingButton: document.querySelector("#stop-training"),
  trainingStatus: document.querySelector("#training-status")
};
